### ISSUE TITLE
이슈 작성시 필독!

### ISSUE THREAD

**Issue by Ryzen72700** [Ryzen72700/Ryzen72700.github.io#1]
**이슈 작성시 필독하세요, 아래의 항목을 지키지 않을시 무통보 삭제가 될수 있음을 알립니다.**

> 네티켓을 지키지 않음.(예의에 어긋나는 말이나 말투, "~해야함? ~있음?" 이정도 까지는 뭐라안함.)
> 광고성 문구
> 연속글(만약 질문이 있을시 하나의 글로 안적고 질문1 올리고 질문2 올리는등 따로따로 계속 올리는것)
> **추후 추가예정**

**Comment by ttakkku** [comment]
네

**Comment by Ryzen72700** [comment]
> 네

네에에엥
### _**눼에에**_

`print("눼에에/YES?")`

**Comment by Ryzen72700** [comment]
> 네

### 네 그래요
**네 그렇다니깐요?**
_저한테 왜그래요?_
`print("자꾸 그러시면\n신고할거에요!`
[ttakkku_is_not_support](https://www.naver.com)
>

**Comment by hayanggames** [comment]
~~늬예늬예~~
알겠슴다

**Comment by Ryzen72700** [comment]
@ttakkku @hayanggames @idoyun027Dorke 늬에늬에
뉘에뉘에
뉘이에뉘이에
예에에ㅔ
**저한테 왜그러세요? 신고할거에요!**
### 신고함
_사과안하면 신고_

> 신고!!
`님 신고할게요수교하새요`
[마춤뻡파괘자 컨셉인데 믿을리가](https://ryzen72700.github.io/)

**Comment by ttakkku** [comment]
This is the issue here, right?

**Comment by ttakkku** [comment]
This is the issue here, right?

**Comment by Ryzen72700** [comment]
@ttakkku yes, this is the issue!!
yeeeaaahhh

**Comment by idoyun027Dorke** [comment]
ㅇㅋ

**Comment by ttakkku** [comment]
This is Not lssues Rules

**Comment by hayanggames** [comment]
뿌슝
