### ISSUE TITLE
봇 명령어에 추가했으면 하는거 제보합니다.

### ISSUE THREAD

**Issue by idoyun027Dorke** [Ryzen72700/Ryzen72700.github.io#2]
=============[ INCLUDE Support ]=============

  ● 지원 / 제보 : ==help를 쳤을때 

저는 INCLUDE에요!

> ==help : 해당 명령어를 모든 명령어를 볼수 있어요!
> ==ping : 제가 Pong! 이라는 문구로 다시 전달해드려요!
> ==미세먼지 : 미세먼지 정보를 확인할수 있어요.
> ==전국날씨 : 전국의 날씨를 확인할수 있어요
> ==명언 : 인생명언을 볼수 있어요
> ==공식사이트 : INCLUDE의 공식 웹사이트를 확인하실수 있습니다.

## 현재 버전 : DEV 1.5 / Python 3.6 / Running in Raspberry Pi3 B+## 

이 중에 ==영화순위가 빠져있습니다.
그리고 ==영화순위를 쳤을때 가능하면 20위 중에 첫 페이지에는 10위만 표시하고 반응으로 다음 페이지 넘기기를 선택하면 다음 페이지로 넘어가서 나머지 20위를 표시하게 했으면 좋겠고, 그리고 출처도 밝혔으면 좋겠습니다.

  ● 종류 :
    ㄴ 봇
  ● 문제 상황 : 
    ㄴ ex. 봇에 일부 기능이 빠져있음.
 
=============[ INCLUDE Support ]=============

   ※※ 작성시 유의사항 ※※
 1. 장난식으로 작성하지 말것.
 2. 광고(홍보)를 작성하지 말것.
 3. 양식을 지우지 말고 쓸것. (지우고 Template에 있는 내용만 들어가게 쓸수 있음.)
 4. 하루에 이슈는 2개로 제한하니 2개 이상 쓰지말것. (새벽 12시, 00:00에 리셋)
 5. 이미 올라와 있는 내용은 이슈를 찾아볼것. (못찾을시에만 작성.)
 6. 중복글을 쓰지말것, (ex. ~로 오류났어요 , ~로 오류났어요 등으로 글 내용을 중복해서 쓰지말것.)
 7. == 추가예정 ==

      【 이 유의사항을 읽지 않고 작성시 무통보 삭제가 이뤄질수 있음을 알립니다 】

**Comment by Ryzen72700** [comment]
다음 업데이트(1905xx)때 추가예정
영화 순위를 반응으로 할수있게 하는건 아직 실력으로 부족하기에 생각해봄.

**Comment by ttakkku** [comment]
@Ryzen72700  
근데 
==영화순위 1 1~10위 까지 그렇게 하면 가능 할 듯

**Comment by Ryzen72700** [comment]
@ttakkku 근데 할줄몰라요

**Comment by ttakkku** [comment]
명령어 추가만 하면 되요

**Comment by Ryzen72700** [comment]
@ttakkku 이게 깃헙에 있는 소스로 만든거라.. 큼 가능할지

**Comment by idoyun027Dorke** [comment]
영화 순위는 기술이 된다면... 반응으로 페이지 넘어가게 할 수 있게 하고 아니면... 그냥 20위 다 표시하게 하던지 또는 ==영화순위 1 이나 2로 해서 나누는것도 괜찮을듯

**Comment by ttakkku** [comment]
저말이 그거였는 데

**Comment by Ryzen72700** [comment]
신기하군 바로바로 달리니

**Comment by ttakkku** [comment]
저가 따로 만들까요?

**Comment by Ryzen72700** [comment]
@ttakkku 아이돈노

**Comment by ttakkku** [comment]
근데 문제는 여기는 봇 소스 올리는 게 아닌ㄷ

**Comment by ttakkku** [comment]
여기는 봇 홈페이지 요

**Comment by Ryzen72700** [comment]
@ttakkku 앗.. 아앗.. 그렇군
잘못 올렸소 ㅇㅅㅇ

**Comment by ttakkku** [comment]
그게 아니라

**Comment by ttakkku** [comment]
근데

https://github.com/ttakkku/Discord.py-Rewrite-Bot

**Comment by ttakkku** [comment]
여기에 올라간 소스 처럼 비슷 해요?

**Comment by ttakkku** [comment]
아니면 리라 전인가

**Comment by Ryzen72700** [comment]
일단 마감을 ㅌㅌ

**Comment by ttakkku** [comment]
저기요

**Comment by ttakkku** [comment]
이거 수정 할 떄 까지 계속 오픈 한다매요

**Comment by Ryzen72700** [comment]
근데 잘못 올렸잖아요

**Comment by ttakkku** [comment]
그래도 수정 할떄까지 기다리죠

**Comment by ttakkku** [comment]
Okay Thx @idoyun027Dorke
